<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fc74bd42-8daf-4a47-85b2-7b69a904519f</elementGuidId>
    <imagePath></imagePath>
    <name>link_policyDocuments</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/footer[1]/div[1]/div[1]/div[1]/p[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'page/${link_policyDocuments_page_id}') and equals(@text,'Refund policy')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_policyDocuments_internalRoleLinkName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Refund policy</value>
        <webElementGuid>901dd510-f4d3-4bfe-bc64-3bc51b5d1f43</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>page/${{link_policyDocuments_page_id}}</value>
        <webElementGuid>901dd510-f4d3-4bfe-bc64-3bc51b5d1f43</webElementGuid>
    </webElementProperties>
</WebElementEntity>